name: Create GitHub Release

on:
  push:
    tags:
      - 'v*.*.*' # Se activa con etiquetas como v1.0.0, v1.2.3, etc.

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necesario para crear releases
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          body: "Release of version ${{ github.ref_name }}"
          draft: false
          prerelease: false

  build-and-upload-customer-app:
    runs-on: ubuntu-latest
    needs: create-release
    permissions:
      contents: write # Necesario para subir artefactos a la release
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'

      - name: Install dependencies
        working-directory: ./customer-app
        run: npm ci

      - name: Build library
        working-directory: ./customer-app
        run: npm run build domain

      - name: Create release artifact
        run: |
          cd ./customer-app/dist/libs/domain
          zip -r ${{ github.workspace }}/customer-app-release.zip .

      - name: Upload Customer App Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./customer-app-release.zip
          asset_name: customer-app-poma-${{ github.ref_name }}.zip
          asset_content_type: application/zip

  build-and-upload-notifications:
    runs-on: ubuntu-latest
    needs: create-release
    permissions:
      contents: write # Necesario para subir artefactos a la release
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'

      - name: Install dependencies
        working-directory: ./notifications
        run: npm ci

      - name: Build library
        working-directory: ./notifications
        run: npm run build domain

      - name: Create release artifact
        run: |
          cd ./notifications/dist/libs/domain
          zip -r ${{ github.workspace }}/notifications-release.zip .

      - name: Upload Notifications Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./notifications-release.zip
          asset_name: notifications-poma-${{ github.ref_name }}.zip
          asset_content_type: application/zip